### ISSUE TITLE
availableForClones reverted: Arithmetic operation resulted in underflow or overflow

### ISSUE THREAD

**Issue by samclassix** [Frankencoin-ZCHF/FrankenCoin#38]
# Error found in ponder running V2

- Event PositionV2:MintingUpdate
- MintingHub V2: Clone, no check for _initMint > 0

```
function clone(
		address owner,
		address parent,
		uint256 _initialCollateral,
		uint256 _initialMint,
		uint40 expiration
	) public validPos(parent) returns (address) {
		address pos = POSITION_FACTORY.clonePosition(parent);
		IPosition child = IPosition(pos);
		child.initialize(parent, expiration);
		zchf.registerPosition(pos);
		IERC20 collateral = child.collateral();
		if (_initialCollateral < child.minimumCollateral()) revert InsufficientCollateral();
		collateral.transferFrom(msg.sender, pos, _initialCollateral); // collateral must still come from sender for security
		emit PositionOpened(owner, address(pos), parent, address(collateral));
		child.mint(owner, _initialMint);
		Ownable(address(child)).transferOwnership(owner);
		return address(pos);
	}
```

### availableForClones 

```

	function availableForClones() external view returns (uint256) {
		// reserve capacity for the original to the extent the owner provided collateral
--->		uint256 unusedPotential = (_collateralBalance() * price) / ONE_DEC18 - minted;
		if (totalMinted + unusedPotential >= limit) {
			return 0;
		} else {
			return limit - totalMinted - unusedPotential;
		}
	}
```

# Trance error

```
1:20:36 AM ERROR indexing   Error while processing 'PositionV2:MintingUpdate' event in 'Polygon' block 64773884

ContractFunctionExecutionError: The contract function "availableForClones" reverted with the following reason:

Arithmetic operation resulted in underflow or overflow.

Contract Call:

address:   0x1D90EA2A1bcCD59E92c4F3e2d98b4064276cf503

function:  availableForClones()

Docs: https://viem.sh/docs/contract/readContract

Version: viem@2.13.8

at /app/src/positionV2.ts:14:2

  12 |

 13 | 	// position updates

> 14 | 	const availableForClones = await client.readContract({

    | 	^

 15 | 		abi: PositionABI,

 16 | 		address: positionAddress,

 17 | 		functionName: 'availableForClones',

caused by: ContractFunctionRevertedError: The contract function "availableForClones" reverted with the following reason:

Arithmetic operation resulted in underflow or overflow.

Version: viem@2.13.8

at file:///app/node_modules/viem/utils/errors/getContractError.ts:62:14

at getContractError (file:///app/node_modules/viem/utils/errors/getContractError.ts:70:5)

at readContract (file:///app/node_modules/viem/actions/public/readContract.ts:128:11)

at processTicksAndRejections (node:internal/process/task_queues:95:5)

at /app/src/positionV2.ts:14:2

at executeLog (file:///app/node_modules/@ponder/core/src/indexing/service.ts:581:5)

at processEvents (file:///app/node_modules/@ponder/core/src/indexing/service.ts:312:24)

at handleEvents (file:///app/node_modules/@ponder/core/src/bin/utils/run.ts:137:12)

at worker (file:///app/node_modules/@ponder/core/src/bin/utils/run.ts:169:28)

Event arguments:

collateral   0

price        8000000000000000000000

minted       8000000000000000000000
```

**Comment by luziusmeisser** [comment]
This could only happen after a forced liquidation of an expired position below the liquidation price. Was fixed in V2.
